name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
        extensions: mysqli

    - name: Validate PHP syntax
      run: find . -name '*.php' -print0 | xargs -0 -n 1 php -l

    - name: Install PHP dependencies
      run: composer install

    - name: Run tests
      run: |
        vendor/bin/phpunit --testdox
